In [1]:
A = [1 2; 3 4; 5 6];
B = [11 12; 13 14; 15 16];
C = [1 1; 2 2];

In [2]:
A * C

ans =

    5    5
   11   11
   17   17



In [3]:
A .* B % each element in A will multiply by a correspond element in B

ans =

   11   24
   39   56
   75   96



In [4]:
A .^ 2 % element square

ans =

    1    4
    9   16
   25   36



In [5]:
v = [1; 2; 3]

v =

   1
   2
   3



In [6]:
1 ./ v % element-wise reciprocal of v, meaning 1/1, 1/2, 1/3

ans =

   1.00000
   0.50000
   0.33333



In [7]:
1 ./ A % element wise inverse of A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [8]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [9]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [10]:
abs(v)

ans =

   1
   2
   3



In [11]:
abs([-1; 2; -3])

ans =

   1
   2
   3



In [12]:
-v

ans =

  -1
  -2
  -3



In [13]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [14]:
v + ones(3,1)

ans =

   2
   3
   4



In [15]:
v + 1

ans =

   2
   3
   4



In [16]:
A'

ans =

   1   3   5
   2   4   6



In [17]:
(A')'

ans =

   1   2
   3   4
   5   6



In [18]:
a = [1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [19]:
val = max(a)

val =  15


In [20]:
[val, ind] = max(a)

val =  15
ind =  2


In [21]:
max(A)

ans =

   5   6



In [22]:
a < 3 % element wise comparison

ans =

  1  0  1  1



In [23]:
A = magic(3) % sum of each rows, columns, diagonal add up to same value

A =

   8   1   6
   3   5   7
   4   9   2



In [24]:
[row,column] = find(A >= 7)

row =

   1
   3
   2

column =

   1
   2
   3



In [25]:
a

a =

    1.00000   15.00000    2.00000    0.50000



In [26]:
sum(a)

ans =  18.500


In [27]:
prod(a) # multiply of all values

ans =  15


In [28]:
floor(a) % round values down

ans =

    1   15    2    0



In [29]:
ceil(a) % round values up

ans =

    1   15    2    1



In [30]:
rand(3)

ans =

   0.83667   0.10854   0.15747
   0.18339   0.40144   0.31210
   0.21656   0.27914   0.48857



In [31]:
A

A =

   8   1   6
   3   5   7
   4   9   2



In [32]:
max(A, [], 1)

ans =

   8   9   7



In [33]:
max(A, [], 2)

ans =

   8
   7
   9



In [34]:
max(max(A))

ans =  9


In [35]:
A(:)

ans =

   8
   3
   4
   1
   5
   9
   6
   7
   2



In [36]:
max(A(:))

ans =  9


In [37]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [38]:
sum(A,1)

ans =

   369   369   369   369   369   369   369   369   369



In [39]:
sum(A,2)

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [40]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [41]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [42]:
pinv(A) % inverse of matrix A

ans =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778

