In [1]:
A = [1 2; 3 4; 5 6];
B = [1 2 3; 4 5 6];

In [2]:
A
B

A =

   1   2
   3   4
   5   6



B =

   1   2   3
   4   5   6



In [3]:
C=[16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]

C =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [4]:
C(:,1:2)

ans =

   16    2
    5   11
    9    7
    4   14



In [8]:
C(1:2,1:4)


ans =

   16    2    3   13
    5   11   10    8



In [9]:
zeros(10,1)

ans =

   0
   0
   0
   0
   0
   0
   0
   0
   0
   0



In [42]:
v=ones(7,1)
w=ones(7,1)
z = 0;
for i = 1:7
  z = z + v(i) * w(i)
end
w*v'

v =

   1
   1
   1
   1
   1
   1
   1



w =

   1
   1
   1
   1
   1
   1
   1



z =  1
z =  2
z =  3
z =  4
z =  5
z =  6
z =  7


ans =

   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1



In [12]:
sum(v.*w)

ans =  7


In [13]:
X=[1 1 1 1 1 1 1;1 1 1 1 1 1 1;1 1 1 1 1 1 1;1 1 1 1 1 1 1;1 1 1 1 1 1 1;1 1 1 1 1 1 1;1 1 1 1 1 1 1;]

X =

   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1



In [32]:
v = zeros(10, 1);
x=ones(10,1)
A=ones(10)
for i = 1:10
  for j = 1:10
    v(i) = v(i) + A(i, j) * x(j);
  end
end

x =

   1
   1
   1
   1
   1
   1
   1
   1
   1
   1



A =

   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1



In [33]:
v

v =

   10
   10
   10
   10
   10
   10
   10
   10
   10
   10



In [24]:
A*x

ans =

   10
   10
   10
   10
   10
   10
   10
   10
   10
   10



In [25]:
x'*A

ans =

   10   10   10   10   10   10   10   10   10   10



In [37]:
sum(A*x)

ans =  100


error: matrix cannot be indexed with .


In [27]:
A.*x

ans =

   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1



In [28]:
A = [1 2; 3 4; 5 6];
B = [1 2 3; 4 5 6];


In [29]:
A'+B
B*A

ans =

    2    5    8
    6    9   12



ans =

   22   28
   49   64



In [43]:
X=ones(7)
for i = 1:7
  for j = 1:7
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end

X =

   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1



In [46]:
A
B
C
X+1 % C=X+1
D
X/4 % D=X/4

A =

   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   0   0   0   0   0   0   0   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1



B =

   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1
   1   1   1   1   1   1   1



C =

   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2



ans =

   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2
   2   2   2   2   2   2   2



D =

   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000



ans =

   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000
   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000   0.25000

